### ISSUE TITLE
remove Fontconfig dependency?

### ISSUE THREAD

**Issue by wadehenning** [dehann/KernelDensityEstimate.jl#1]
I am very interested in trying your KernelDensityEstimate package, but I am having trouble loading Fontconfig on my Windows machine.  If I fork this and remove the KDEPlotting01.jl file, will this eliminate the need for the dependencies?  Your plots look great and I would like to try them, I am most interested in the numerical results.

Thanks,
Wade

**Comment by dehann** [comment]
Hi @wadehenning, yes I want to separate out the plotting and modify the underlying structure of the package quite a bit. Functionality should be unchanged though (will warn if API changes a little). I unfortunately do not have too much experience with this on Windows, but was going to run it at some point in the near future on Windows, so will be interested to hear what you find... I'd say go ahead a isolate the Fontconfig dependency.

I don't see any Windows related issues on dcjones/Fontconfig.jl yet. So not sure on the status to fix the original issue.

**Comment by dehann** [comment]
@wadehenning, I should add that the Fontconfig dependency is related to Gadfly package (which I use for plotting). Can you run Gadfly on its own and generate plots? Say, plot(y=randn(10), Geom.point)  ? I was using Fontconfig to draw to PDF. Cairo and Fontconfig are not strictly required.

**Comment by wadehenning** [comment]
@dehann , Gadfly has also quit working due to the same Fontconfig issue ('libfontconfig' will not precompile).  It's a real bummer; I have some new code of my own I would like to visualize the results for but I use the Junolab Atom IDE and am having trouble plotting anything! The Juno team has recently added Plotlyjs functionality and it almost works like it should.

**Comment by wadehenning** [comment]
@dehann, I removed the references to Gadfly and Fontconfig and removed the KDEPlotting01.jl function.  Works great.  I have some questions about the package usage, but I will open another issue.  
Thanks.
