### ISSUE TITLE
How to modify the kernel ?

### ISSUE THREAD

**Issue by Oudjane** [dehann/KernelDensityEstimate.jl#20]
Hi,
I couldn't figure out how to modify the kernel. In particular, I would like to be able to compute gradients of the density. 
Thank you,

Nadia

**Comment by dehann** [comment]
Hi Nadia,

Changing kernels is possible, but not really built out in this package yet. I will keep in mind for future development. The main purpose of this package is to approximate the product between Gaussian kernel density estimates. The [KernelDensity.jl](http://github.com/JuliaStats/KernelDensity.jl) package is more mature (although they do not estimate products) and may have more of the tools you need right now.

However, for your second question, calculating the gradients of a KDE in this package will be easiest through numerical differencing:
```julia
h = 1e-5
p = kde!(randn(100))
ep = evaluateDualTree(p,[1.0; 1+h])
dpdx = diff(ep)/h
```
Analytic derivative is also possible, but not all the functions are clearly defined for a general API yet. I will keep this in mind going forward also.

Thanks

**Comment by Oudjane** [comment]
Thank you very much for your answer !

Unfortunately the KernelDensity.jl package is not able to consider d-dimensional density estimation for d>=3.
For the gradient, thank you, automatic differencing could be an issue. I will try it but I am worried about the variance of the resulting estimate. I thought it would be more efficient to pass the gaussian kernel derivative as a new kernel.
Thank you again for all,

Nadia
